Stacktrace is not shown when giving wrong command
shyndman/pubx pull request #1
Opened 2019-07-24 16:09 UTC by Vanethos

Do not show the stacktrace when giving a wrong command

Changed so that the output is of format:

```
$ dart ./bin/pubx.dart asdasd
Could not find a command named "asdasd".

Usage: pubx <command> [arguments]

Global options:
-h, --help    Print this usage information.

Available commands:
  help     Display help information for pubx.
  search   Searches pub.dev for packages
  view     View information about a pub.dev package

Run "pubx help <command>" for more information about a command.

```

2019-07-24 17:28 UTC, shyndman requested changes
Wonderful. Nice job on the exit code too. 🙂

Mind using await instead?

Also, rethrow is preferable to preserve the stack.

2019-07-24 17:34 UTC, Vanethos commented
Thanks!

May I ask how do you want to use the `await`? Are you saying in the `runner.run()`method?

In that case, if an error is thrown, it's still going to throw an exception unless we use a try/catch block, if I'm correct.

Ah, you want to preserve the stack? This PR was created to be the opposite of that, giving the user a brief message and hiding the stacktrace

2019-07-24 17:39 UTC, shyndman commented
Right, await with a try-catch on run. 

And a rethrow if the exception is not a UsageException. Where you throw now.  Otherwise, suppress as you're doing. 

I'd like to know the origin the failure if we're dealing with a case other than usage.

2019-07-24 17:41 UTC, Vanethos commented
May I ask why not using the `catchError` instead of the `try-catch`? (in the meantime I'll make the changes)

2019-07-24 17:44 UTC, Vanethos commented
Currently, the code does the following:

If the error is not a `UsageException`, the stack is shown

Example: turn off the internet and try to view a package

```
notification_permissions: 0.4.0
Author: GonÃ§alo Palma <solid.goncalo@gmail.com>
A plugin to check and ask for notification permissions on Android and iOS
https://pub.dev/packages/notification_permissions
➜  pubx git:(master) ✗ dart ./bin/pubx.dart view notification_permissions
notification_permissions: 0.4.0
A plugin to check and ask for notification permissions on Android and iOS
https://pub.dev/packages/notification_permissions
➜  pubx git:(PR-1-catch-error) ✗ dart ./bin/pubx.dart view notification_permissions
Unhandled exception:
SocketException: Failed host lookup: 'pub.dartlang.org' (OS Error: nodename nor servname provided, or not known, errno = 8)
#0      IOClient.send (package:http/src/io_client.dart:33:23)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
<asynchronous suspension>
#2      BaseClient.get (package:http/src/base_client.dart:32:7)
#3      get.<anonymous closure> (package:http/http.dart:46:36)
#4      _withClient (package:http/http.dart:166:20)
<asynchronous suspension>
#5      get (package:http/http.dart:46:5)
#6      view (package:pubx/src/api.dart:25:26)
<asynchronous suspension>
#7      ViewCommand.run (package:pubx/src/view.dart:37:35)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#10     new Future.sync (dart:async/future.dart:224:31)
#11     CommandRunner.run (package:args/command_runner.dart:112:14)
#12     main (file:///Users/goncalopalma/FlutterProjects/openSource/pubx/bin/pubx.dart:11:10)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```

2019-07-24 17:55 UTC, shyndman commented
Ah, that's good, and slightly unexpected. Dart Style recommends using the rethrow to preserve stack, so I'm not sure why it would be preserved in its absence. Maybe because this is outside of a catch? /shrug

In general, I prefer an async-await unless there's some need to pass around the `Future`. If I want the results of a computation in the caller (or in this case the failure), await is a more consistent way to express that. The semantics are identical to non-asynchronous code, and that's one less concept to think about.

If you've ever read Bob Nystrom's [What Color is Your Function?](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/), it gives a pretty good description of why async-await is a win. It was written before Dart or JS had await, and even before Bob worked on Flutter I think, but the point remains true.

2019-07-25 08:41 UTC, Vanethos commented
Done!

First: thank you for the explanation.

I can see your point, specially `The semantics are identical to non-asynchronous code, and that's one less concept to think about.`

For me it was "strange" to do that since I was so focused on the Dart-way of doing things with Futures, but I get your point of view.

Sorry for so many questions! But I was genuinely intrigued as to why and wanted to take this opportunity to learn your point of view on the matter.

2019-07-25 09:17 UTC, shyndman commented
No problem. Thanks for the contribution, and I added your email. :)

2019-07-25 09:17 UTC, merged